### ISSUE TITLE
Data lineage management with YesWorkflow tool

### ISSUE THREAD

**Issue by john-judge** [ksscheuer/Jackson_Lab#1]
This is just to give background on the purpose of the `data_lineage` branch.

`YesWorkflow` is a tool designed for scientific scripting: 
- [Arxiv link](https://arxiv.org/pdf/1502.02403.pdf)
- [Github repository](https://github.com/yesworkflow-org/yw-prototypes)

Data provenance / data lineage tools help track and describe methodology with easily communicable visualizations and automate a couple steps of documentation. The overall goal is to improve data analysis reproducibility. 

As an example I added code annotations to the Part 1 script, which then automatically generated this process diagram to visualize input/output and data dependency between the steps of data processing.

![cluster_part1](https://user-images.githubusercontent.com/40705003/115120057-0b9ea800-9f71-11eb-976c-04f71cef6cd6.png)

**Comment by ksscheuer** [comment]
I've never seen this tool before, but I love it! This is actually a great way to clarify what we're doing.
